### PR TITLE
prev_prime, next_prime

### PR DESCRIPTION
**Pull request by SergBobrovsky**
Comments for such tiny and simple functions are mockingly detailed. It's like trolling )

### CODE REVIEW

**Comment by mhostetter** [comment]
I think you need this commit on #50 to help it pass its unit tests, not a separate PR.

**Comment by SergBobrovsky** [comment]
- Can you break your changes in single PRs? 
- Yes
- I think you need this commit on #50 to help it pass its unit tests, not a separate PR.
- ORLY? 
> Your previous PR #46 just had code at the bottom that wasn't ready to merge.

You will laugh, but PR#46 was consistent and would pass the test - if remove everything all above it. The aim of PR#46 was to show my view of the entire architecture of the module.
Would it be constructive to replace all yous code to mine? No, it'll be looks strange. Would it good to ignore PR#46 considering my comment on it?

> There is no point in trying to merge your and my code with separate commits - too much has been redone and reorganized, and the diff utility does not allow anybody to figure it out.
I just added my code in one piece at the bottom of the file, without changing anything at the top. This means that the PR will not pass the tests - it doesn't matter. This means that you can delete those variants of the functions of the same name that you like less.

**Comment by mhostetter** [comment]
I don't know what you want. I asked for atomic PRs -- something that changes one thing. Like for instance, adding `primes()`. You need to "fix" anything you break with the new addition.

If you want something merged, submit a PR, ensures that it passes the tests, and we can discuss it.

**Comment by SergBobrovsky** [comment]
So what's wrong with PR#50 now? It passed tests? Let's speak about.

**Pull request closed without merging**
