### PR TITLE
Add support for numpy 1.22

### PR DESCRIPTION
**Pull request by iyanmv**
Solves #365

### CODE REVIEW

**Comment by mhostetter** [comment]
@iyanmv I like this thanks! I was just checking today to see about when Numba / NumPy might support Python 3.11 (I see people trying to install `galois` with Python 3.11). But this is very welcome, indeed.

Do you think it's worth a published release allowing users to get the latest everything? I don't have any another releases in the queue at this moment. So maybe it could be a small-ish release.

**Comment by mhostetter** [comment]
I also want to check that NumPy 1.22 doesn't throw any deprecation warnings or something similar. I've had that happen before. I'm testing on my machine now.  Also curious if the test results have any warnings listed.

**Comment by iyanmv** [comment]
I guess it's fine to have a small release, but it's your call :wink: 

Interesting... I only got one warning, but nothing related with numpy or scipy.

```
============================================================ warnings summary =============================================================
../../../../../../usr/lib/python3.10/site-packages/pytest_asyncio/plugin.py:191
  /usr/lib/python3.10/site-packages/pytest_asyncio/plugin.py:191: DeprecationWarning: The 'asyncio_mode' default value will change to 'strict' in future, please explicitly use 'asyncio_mode=strict' or 'asyncio_mode=auto' in pytest configuration file.
    config.issue_config_time_warning(LEGACY_MODE, stacklevel=2)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=============================================== 7268 passed, 1 warning in 275.54s (0:04:35) ===============================================
```
I will run them again in a Arch chroot instead of a python env.

**Comment by mhostetter** [comment]
I'm ready to merge. Let me know when you are.

**Pull request merged**
