### PR TITLE
Comply with PEP 561

### LINKED ISSUE #480: Add `py.typed` marker to the project so that tools like mypy recognize the type definitons
As per [PEP 561](https://peps.python.org/pep-0561), packages which have inline types need to ship a file named `py.typed` in the root of the package directory tree.

### PR DESCRIPTION
**Pull request by mhostetter**
Fixes #480

### CODE REVIEW

**Comment by mhostetter** [comment]
@Minnerlas can you install the `.whl` file inside this zip (built from this branch) and see if it provides the correct flags to `mypy`. And if the types in `galois` play well with `mypy`? I really have never tested with `mypy`. Thanks.

[dist-pr481.zip](https://github.com/mhostetter/galois/files/11413151/dist-pr481.zip)

**Comment by mhostetter** [comment]
I verified this is packaged correctly and works with `mypy`.

```python
# file: test.py
import galois
GF = galois.GF(256.0)
```

### Before

```python
PS C:\Users\matth> python3 -m mypy test.py
test.py:1: error: Skipping analyzing "galois": module is installed, but missing library stubs or py.typed marker  [import]
test.py:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 1 source file)
```

### After

```python
PS C:\Users\matth> python3 -m mypy test.py
test.py:3: error: No overload variant of "GF" matches argument type "float"  [call-overload]
test.py:3: note: Possible overload variants:
test.py:3: note:     def GF(order: int, *, irreducible_poly: Optional[PolyLike] = ..., primitive_element: Union[int, PolyLike, None] = ..., verify: bool = ..., compile: Optional[Literal['auto', 'jit-lookup', 'jit-calculate', 'python-calculate']] = ..., repr: Optional[Literal['int', 'poly', 'power']] = ...) -> Type[FieldArray]
test.py:3: note:     def GF(characteristic: int, degree: int, *, irreducible_poly: Optional[PolyLike] = ..., primitive_element: Union[int, PolyLike, None] = ..., verify: bool = ..., compile: Optional[Literal['auto', 'jit-lookup', 'jit-calculate', 'python-calculate']] = ..., repr: Optional[Literal['int', 'poly', 'power']] = ...) -> Type[FieldArray]
Found 1 error in 1 file (checked 1 source file)
```

**Comment by Minnerlas** [comment]
I am sorry, I haven't seen that I was tagged until now. Thanks for the quick fix though!

**Comment by mhostetter** [comment]
No problem. Open another issue if v0.3.5 has issues with `mypy`.

**Pull request merged**
