### PR TITLE
A bit algo reorganizatin

### PR DESCRIPTION
**Pull request by SergBobrovsky**
trace() is fast enough, and derivative functions doesn't needs @nimba.jit

### CODE REVIEW

**Comment by mhostetter** [comment]
Thank you for the pull request.

I just pushed a modification to the GitHub Action workflows that should enable the linting and unit testing to run on pull requests. Can you rebase your branch off of `master` and force push? That should trigger the CI tests.

**Comment by SergBobrovsky** [comment]
I better will close PR, cause it is important to clear for me architectural aspects of project before. When You'll have a time, let's discuss.

**Comment by mhostetter** [comment]
I like the idea of the PR. Factoring and prime factoring for arbitrarily large integers is desired. I just put in a simple algorithm to speed up development, with the intent to optimize later.

Why don't you open a new PR and state the desired improvement you'd like. We can discuss it (I'm sure it's good). And then you can push commits (and hopefully the CI will run on your new PR).

**Comment by mhostetter** [comment]
@SergBobrovsky Also, I'm actively developing/structuring the package. So my documentation isn't complete yet; in fact, it's very ad hoc. Any feedback or thoughts on the package or API would be appreciated. The little documentation that does exist is published to [readthedocs](https://galois.readthedocs.io/en/v0.0.8/), in case you haven't seen it already.

**Comment by SergBobrovsky** [comment]
At first I wonder, where the lies border between numpy code and ordinary
python code? For what do You plans to use numpy mass operations? It'
important, cause it's good idea to separate this kinds of code and minimize
data conversions.

чт, 11 мар. 2021 г. в 19:16, Matt Hostetter ***@***.***>:

**Pull request closed without merging**
