### PR TITLE
some code reorganization around `primes`

### PR DESCRIPTION
**Pull request by SergBobrovsky**

### CODE REVIEW

**Comment by mhostetter** [comment]
Is the goal of this PR to support prime factorization for arbitrarily-large integers, not just up to the fixed-size `PRIMES` lookup table I had?

What algorithms are used in `primes()` and `trace()`? Could you provide reference links? Thanks.

**Comment by SergBobrovsky** [comment]
> Is the goal of this PR to support prime factorization for
arbitrarily-large integers, not just up to the fixed-size PRIMES lookup
table I had?
- Yes, Eratosthenes sieve is not a rocket science (it's primes about).
> What algorithms are used in trace()? Could you provide reference links?
Ouh, did You read the body of trace() function? Do You really need
professional reference? I thought to learn something from you, but you
discouraged me.

**Comment by mhostetter** [comment]
Hahaha if you're going to be rude I won't work with you. There are many sieve algorithms for primes. It was a fair question. It was not obvious which you implemented. This code is not a bastion of readability. `chanks`? A random `bytearray` of 0s and 1s?

```
    chanks = (limit + 29) // 30
    lim, sieve = chanks * 15 - 1, bytearray(b'\0\0\1\0\1\1\0\1\1\0\1\0\0\1\1') * chanks
    for b, p in zip(sieve, range(3, int(sqrt(chanks * 30 + 1)) + 1, 2)):
        if b:
            pp = (p * p - 3) // 2
            sieve[pp::p] = b'\0' * ((lim - pp) // p + 1)
    return [2, 3, 5, *(p for b, p in zip(sieve, range(3, limit, 2)) if b)]
```

**Comment by SergBobrovsky** [comment]
> Could you provide reference links
No, I couldn't. Both functions primes() and trace() were written by my own,
like many other(not all). primes() is a bit complicated, but very efficient
on speed and memory consumption for pure python code. Saing about "a random
bytearray of 0s and 1s" You depreciating obviosly working code.
If You need - I can comment this code.
trace() is absolutely clear, and if you avoid to read code - this may be a
real obsticle for cooperation.

**Comment by mhostetter** [comment]
I've been working on reorganizing the project. If you rebase off of `master` and add the prime sieve in a function called `primes()` and comment it, I'll merge it in.

**Comment by mhostetter** [comment]
This appears to be a duplicate with #18. Could you consolidate the pull requests into one PR?

**Pull request closed without merging**
