### PR TITLE
Hamming codes

### PR DESCRIPTION
**Pull request by abhishekmittal15**
Hi, just opened a PR on the issue #152 . 
I had a doubt regarding the construction of the parity check and generator matrix
The idea was to brute force the generation of the parity check matrix columns and then convert  $H=[-P^T|I]$ to $G=[I|P^T]$. 
This works for normal Hamming codes as the parity check matrix contains the identity columns and I can swap them to send them to the end and hence I am able to convert it to systematic form. 
But in the case of extended Hamming codes, there are no identity columns anymore so this method of swapping wont work. 
So I just decided to take the inverse of the square matrix at the end of the parity check matrix to get an identity matrix, but the square matrix at the end of the parity check matrix might not be full rank, so this method also doesnt work. 
Any suggestions on how I can get a systematic parity check matrix for extended Hamming codes?

By identity columns I am referring to the columns of the identity matrix

### CODE REVIEW

**Comment by mhostetter** [comment]
I think you want to take the **H** from the (7, 4) code and add a row of ones (sum the codeword symbols). Then you want to solve for an **I** on the right of the **H** matrix.

Currently, I have [`FieldArray.row_reduce()`](https://mhostetter.github.io/galois/latest/api/galois.FieldArray.row_reduce/) which solves for an **I** on the *left*. I was considering adding an option to solve for an **I** on the right. Perhaps, I can submit a quick PR to add that feature.

image

**Comment by mhostetter** [comment]
In #426, I added the ability to solve for an I on the right side of matrix (https://mhostetter.github.io/galois/latest/api/galois.FieldArray.row_reduce/). You can use that to standardize **H** when in systematic form. You should rebase your branch to `generalize-bch-and-rs`.

**Comment by mhostetter** [comment]
Oops! I didn't mean to close this PR... I merged my `generalize-bch-and-rs` branch into `0.2.x`. @abhishekmittal15 can you rebase off of `0.2.x` and re-open?

**Comment by abhishekmittal15** [comment]
Yea sure I will rebase off of the new version and continue my work from there

**Pull request closed without merging**
