### PR TITLE
Removes deprecation warnings from numpy 1.25

### PR DESCRIPTION
**Pull request by iyanmv**
Related to #491.

Not sure if this affects older supported versions, and it's also not that easy for me to check locally, so let's see with the Github CI.

### CODE REVIEW

**Comment by mhostetter** [comment]
I know what's going on with the docs failing to build. It's from a breaking change in `pydantic` that affected `sphinx-immaterial`.

I'll submit a PR to fix the docs and merge it to `release/0.3.x`. Then you can rebase off of that.

**Comment by iyanmv** [comment]
> I know what's going on with the docs failing to build. It's from a breaking change in `pydantic` that affected `sphinx-immaterial`.

Good because I was totally lost 😅

**Comment by mhostetter** [comment]
Ok, you should be able to rebase off of `release/0.3.x` now and your build should pass.

**Comment by mhostetter** [comment]
Sweet! Is this good to merge now? I'm guessing we'll do another PR for full Numba 0.58 support?

**Comment by iyanmv** [comment]
Yes, I think so.

**Pull request merged**
