### PR TITLE
Check for and handle None docstrings

### PR DESCRIPTION
**Pull request by jcharlong**
This PR addresses https://github.com/mhostetter/galois/issues/544

I confirmed that I ran into the issue by running tests w/ `python -OO -m pytest tests/`. The issue is resolved & all tests completed after this update.

Let me know if there are any version or release notes I should be handling in this PR. I could not find any guidelines on this for developers in the repository's documentation.

### CODE REVIEW

**Comment by mhostetter** [comment]
Can you rebase this off of [mhostetter:release/0.3.x](https://github.com/mhostetter/galois/tree/release/0.3.x)? That is required to pass the tests.

**Comment by jcharlong** [comment]
Sure thing, just pushed after rebasing.

**Comment by mhostetter** [comment]
The latest macos CI runners have screwed things. I've got to debug this before the tests can work. Hang tight.

**Comment by mhostetter** [comment]
Can you rebase off of `release/0.3.x` again? (I would do it, but I don't know how for you branch.) I think we should be good now.

**Comment by jcharlong** [comment]
Sure thing, just pushed after rebasing. Thanks for your quick turn around time in debugging, I appreciate it.

**Comment by mhostetter** [comment]
Thanks! I'll push a new release tonight.

**Comment by jcharlong** [comment]
Great, thanks again for the quick support.

**Pull request merged**
