### PR TITLE
Convert to `pyproject.toml` and a `src/` folder

### PR DESCRIPTION
**Pull request by mhostetter**
This PR modifies the packaging of `galois`.

Firstly, it converts from using `setup.py` and `setup.cfg` to exclusively using `pyproject.toml`. This single configuration file is the current recommendation, see [PEP 518](https://peps.python.org/pep-0518/) and [PEP 621](https://peps.python.org/pep-0621/). The build still uses `setuptools` as the packager. And since [v64.0.0](https://setuptools.pypa.io/en/latest/history.html#v64-0-0), `setuptools` now supports editable installs with `pyproject.toml`. Editable installs are basically essential for developers.

Secondly, this PR converts from a static version file `galois/version.txt` (which was updated by a GitHub Action during release) and a reader module `galois/_version.py` to [`setuptools_scm`](https://github.com/pypa/setuptools_scm) which creates a version file `galois/_version.py` at build-/install-time. Using `setuptools_scm` enables support for intermediate versions. For instance, I currently have `0.0.33.dev13+g59adb34`, which is 13 commits past `v0.0.32` with git commit hash 59adb34.

And thirdly, motivated by Iyán's discussion https://github.com/mhostetter/galois/discussions/399, this PR moves the `galois/` source tree to `src/galois/`. This mainly prevents unit tests from being run against the local source code and not an installed version. (Running `pytest` from the repository root can "see" the `galois/` source folder and import it. And it will import it *before* the globally installed version because `.` is first in `PYTHONPATH`!) This ensures unit tests are run against the *packaged* code, not the local source. From what I can tell, this is the generally-accepted *better* approach.

### CODE REVIEW

**Comment by mhostetter** [comment]
Hey @iyanmv and @ChrisPattison, would you mind reviewing this PR?

I know you both maintain a Linux package of `galois` for different OSes. This PR modifies the packaging and structure of the library. Can you let me know if you forsee any issues or have any suggestions / modifications? Thanks.

**Comment by ChrisPattison** [comment]
Hi @mhostetter , thanks for checking. I have this branch building in nix, and everything is good on my end. 

Setuptools in the nix environment was complaining about `project.version` not being PEP 440 compliant, so I just patched it with the hardcoded version number. We already have this information as part of the packaging process, so it's not a problem on my end. 

I guess PEP 440 is just more or less that `project.version` needs to be a literal string

**Comment by mhostetter** [comment]
Thanks for verifying your build @ChrisPattison.

It's likely complaining because this branch isn't an officially-released version. That is, `HEAD` is not tagged with a version. The current version string for this branch is `0.0.33.dev15+gc822914`. When a release is made, a version tag will be added and `setuptools_scm` should create the `0.0.33` version, which should be PEP 440 compliant.

If you're interested in running a test, you could add a local tag to this branch with `v0.0.33` (or similar) and see if the nix builds without needing to patch `project.version`.

**Comment by iyanmv** [comment]
Sorry to join later to this party. I was traveling for the last few weeks and I disconnected a little bit from the computer in general and github in particular. Congrats on the first beta release by the way!

I will update the PKGBUILDs I maintain and do a few tests with the code I have using `galois`. If I see anything, I will let you know :wink:

**Comment by iyanmv** [comment]
No issues with the [-git](https://aur.archlinux.org/packages/python-galois-git) version, but I have an issue with the new release tarballs. Maybe this is the intended behavior, so please let me know.

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 351, in <module>
    main()
  File "/usr/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 333, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/usr/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
    return hook(config_settings)
  File "/usr/lib/python3.10/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
    return self._get_build_requires(
  File "/usr/lib/python3.10/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
    self.run_setup()
  File "/usr/lib/python3.10/site-packages/setuptools/build_meta.py", line 281, in run_setup
    super(_BuildMetaLegacyBackend,
  File "/usr/lib/python3.10/site-packages/setuptools/build_meta.py", line 174, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 109, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 477, in __init__
    _Distribution.__init__(
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 293, in __init__
    self.finalize_options()
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 901, in finalize_options
    ep(self)
  File "/usr/lib/python3.10/site-packages/setuptools_scm/integration.py", line 123, in infer_version
    _assign_version(dist, config)
  File "/usr/lib/python3.10/site-packages/setuptools_scm/integration.py", line 62, in _assign_version
    _version_missing(config)
  File "/usr/lib/python3.10/site-packages/setuptools_scm/__init__.py", line 109, in _version_missing
    raise LookupError(
LookupError: setuptools-scm was unable to detect version for /build/python-galois/src/galois-0.1.1.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
* Getting dependencies for wheel...

ERROR Backend subprocess exited when trying to invoke get_requires_for_build_wheel
```
As the error mentions, by using the PyPI tarballs `setuptools_scm` can read the version without problems. For now, I will replace the source array with the tarball from PyPI.

**Comment by mhostetter** [comment]
@iyanmv I believe that is expected behavior. `setuptools_scm` creates `src/galois/_version.py` at build-time or install-time. That file is not version controlled. The version populated in `_version.py` is determined from the latest git tag.

My understanding is that the GitHub release tarball contains just source code from the tagged release (without the .git/ folder). In that case, `setuptools_scm` doesn't have `_vesion.py` or any git info to create `_version.py`. The source tarball uploaded to PyPI should have the `_version.py` file created during package build.

**Pull request merged**
