### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by istankovic**

### CODE REVIEW

**Comment by mhostetter** [comment]
Oops, I'm sorry I just saw this. I'll approve it shortly. Thanks for fix!

**Comment by mhostetter** [comment]
Hey @istankovic, I tried to point this pull request to `release/0.3.x`, but I seem to have messed it up.

Would you mind rebasing off of `release/0.3.x` and force pushing? Or close this and submit a new PR based off of `release/0.3.x`? Thanks.

**Comment by istankovic** [comment]
> Hey @istankovic, I tried to point this pull request to `release/0.3.x`, but I seem to have messed it up.
> 
> Would you mind rebasing off of `release/0.3.x` and force pushing? 

Done.

**Comment by mhostetter** [comment]
@istankovic thanks again for the patch. It will be released in v0.3.7.

**Pull request merged**
