### PR TITLE
Use new numpy.random.default_rng()

### PR DESCRIPTION
**Pull request by iyanmv**
New code should use the `integers` method of a `default_rng()` instance of `numpy.random.randint` according to [numpy documentation](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html). See also [this](https://albertcthomas.github.io/good-practices-random-number-generators/).

In addition, a `seed` can be provided directly to the `Random()` constructor for reproducible research. Before, one could use the global seed `numpy.random.seed()` method (although, [also a legacy function](https://numpy.org/doc/stable/reference/random/generated/numpy.random.seed.html)), but this would silently "fail" for large field with `dtype` `np.object_`, where the seed should be set with `random.seed` method from the standard library.

If you like this idea, I can include some tests in further commits, and revise the docs as well.

### CODE REVIEW

**Comment by mhostetter** [comment]
Yes, I like this! It seems like a more proper way to use NumPy and the random submodule. Admittedly, I used the "legacy" `np.random.seed()` once as a global seed, but I realize this is not best practice.

Did you intentionally terminate the tests? I've noticed lately that occasionally GitHub Actions will stall (almost like a freeze) and not recover. Not sure why. Can you (as a contributor) "re-run" all the jobs? I know I can as the maintainer. I'll restart them now and see if they make it through.

I'll do a code review when you're finished. The only suggestion I'd make so far is to order the kwargs `seed=None, dtype=None`. Sorry if that's petty.

**Comment by iyanmv** [comment]
I didn't terminate the tests. Actually, I didn't realize they failed until I saw your comment now.

> I'll do a code review when you're finished. The only suggestion I'd make so far is to order the kwargs seed=None, dtype=None. Sorry if that's petty.

Okay, great! Then I will write some tests tonight. The order of `seed` and `dtype` was done on purpose because I was afraid of breaking some tests, but probably they are always written with the keyword anyways. But I didn't check to be honest. But sure, I will change the order, no problem.

**Comment by iyanmv** [comment]
It failed again on some platforms.

```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! KeyboardInterrupt !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\numpy\core\fromnumeric.py:90: KeyboardInterrupt
(to show a full traceback on KeyboardInterrupt use --full-trace)
===================== 2564 passed in 21542.49s (5:59:02) ======================
Error: The operation was canceled.
```

Weird...

And btw: no, I cannot "re-run" the jobs.

**Comment by mhostetter** [comment]
I looked through a couple of outputs; here's a screenshot of one. By the way, do you have access to the outputs of the tests (like below)?

image

They all seem to be failing in `tests/fields/test_instantiation.py`. I'm not sure if that's related to your change.

**Comment by mhostetter** [comment]
One thing you could try is to just run the unit tests in `tests/fields/test_instantiation.py`. Add a test commit that changes `.github/workflows/test.yml` lines 50, 110, and 144 to say `tests/fields/test_instantiation.py` instead of `tests/`. That will make all the tests run faster. We can delete or overwrite that commit later.

Also if you "force push" to your branch that should re-trigger the running of all the tests.

I'm going to manually re-run the tests from your other PR to make sure this isn't a temporary GitHub Actions quirk.

**Comment by iyanmv** [comment]
> By the way, do you have access to the outputs of the tests (like below)?

Yes, yes, I can check those as well. I will have a look. Also, I would like to add a few more tests checking the actual values for a fixed seed and all the different fields, but I will not have time today. Probably tomorrow I will be able to continue. And also ,figuring out why `tests/fields/test_instantiation.py` is not working.

**Comment by iyanmv** [comment]
Mmm... it looks like it's a GitHub issue. What do you think?

**Comment by mhostetter** [comment]
I just re-ran the full test suite from your other PR -- that worked. Just now you ran `tests/fields/test_instantiation.py` only and that worked. However, previously the full test suite stalled. Like I said before, sometimes I've seen GitHub Actions be temperamental.

Let's do this: remove your "only run test_instantiation.py" commit (you can `git rebase -i master` and "drop" that commit and then force push to origin). Let's see if the full test suite can make it through. I suspect it will.

**Comment by iyanmv** [comment]
Okay, I will do the rebase, and continue with the reproducible test tomorrow.

**Comment by iyanmv** [comment]
Okay, so at the end I wrote the test, because tomorrow I will probably have even less time. So I guess with last commit you can have a look, and review it. I was not sure where to put the actual arrays, so I created a dictionary at the beginning of the file. What do you think?

**Comment by iyanmv** [comment]
I tried running everything locally with [act](https://github.com/nektos/act) and it doesn't fail. At this point, I think it's a GitHub's issue. I will leave this rest for a while, and we can continue in a few days.

**Comment by mhostetter** [comment]
Yeah, it is a bit puzzling... The only thing that gives me pause is it *consistently* fails all the tests at around the same point in the tests.

I wonder if since every `FieldArray.Random()` call will generate a new seed, and `Random()` calls are very common in the unit tests, that maybe that system can't generate enough entropy to construct a new random seed after N time? I don't know, I'm grasping at straws...

image

**Comment by iyanmv** [comment]
> I wonder if since every FieldArray.Random() call will generate a new seed, and Random() calls are very common in the unit tests, that maybe that system can't generate enough entropy to construct a new random seed after N time? I don't know, I'm grasping at straws...

But before my changes, you were doing the same with the legacy way to get random numbers, and you were also not specifying the seed (if not specified, default is `None`), so if it is an entropy pool issue (which I don't think is the case on these servers where they run these actions), you would have it before my changes as well.

Also, if I run that test alone, it works. So it looks like some kind of limit is reached, and tests freeze. Maybe we can try, just once, to run everything sequentially?

**Comment by iyanmv** [comment]
Okay, I found these two options that may help to debug this: `max-parallel` and `fail-fast`. Let's see...

**Comment by mhostetter** [comment]
> But before my changes, you were doing the same with the legacy way to get random numbers, and you were also not specifying the seed (if not specified, default is None), so if it is an entropy pool issue (which I don't think is the case on these servers where they run these actions), you would have it before my changes as well.

My understanding, and I could be wrong, is that before when NumPy was imported a global RNG was seeded *once*. Then subsequent calls to `np.random.randint()` would "step" the RNG state and generate new random values, but not re-seed the RNG each call.

What you currently have re-seeds the RNG every time `seed=None`, which is how all the unit tests invoke `FieldArray.Random()`.

If my hypothesis is correct (that the re-seeding and lack of entropy to generate a new seed is the issue), then I would expect adding a `seed = 123456798` line in `Random()` would resolve the issues and the tests would pass as normal. Might be a good test to try? 🤷 

I'm suggesting adding something like this as a test:

```python

    @classmethod
    def Random(cls, shape=(), low=0, high=None, seed=None, dtype=None):
        dtype = cls._get_dtype(dtype)
        high = cls.order if high is None else high
        if not 0 <= low < high <= cls.order:
            raise ValueError(f"Arguments must satisfy `0 <= low < high <= order`, not `0 <= {low} < {high} <= {cls.order}`.")

        if not isinstance(seed, int) and seed is not None:
            raise ValueError("Seed must be an integer or None.")

        ###############################################################################################
        seed = 123456789  # Hardcode this to prevent calling `np.random.default_rng(None)`
        ###############################################################################################
 
        if dtype != np.object_:
            rng = np.random.default_rng(seed)
            array = rng.integers(low, high, shape, dtype=dtype)
        else:
            array = np.empty(shape, dtype=dtype)
            iterator = np.nditer(array, flags=["multi_index", "refs_ok"])
            random.seed(seed)
            for _ in iterator:
                array[iterator.multi_index] = random.randint(low, high - 1)

        return array.view(cls)
```

**Comment by iyanmv** [comment]
> My understanding, and I could be wrong, is that before when NumPy was imported a global RNG was seeded once. Then subsequent calls to np.random.randint() would "step" the RNG state and generate new random values, but not re-seed the RNG each call.

Ah, yes yes, you are totally right!

I found [this](https://github.com/actions/virtual-environments/issues/672) that I think it's relevant, but should have been fixed by now... What I'm curious is why some combinations of dependencies, OS and python version fail, while others don't.

**Comment by iyanmv** [comment]
I really don't understand why these GitHub images run out of entropy... At first I thought that since they run Ubuntu 20.04, they would have issues without `rng-tools` or `haveged` because of `linux<5.6`. But now I realized that `ubuntu-latest` in fact uses [`linux 5.11`](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md). Unless these Azure images change the behavior of `/dev/random` and `/dev/urandom`, there should never run out of entropy.

As a side note, I also realized that `test_linalg.py` can potentially exceed the 6 hours max of GitHub because many of the tests initialize randomly, so sometimes, `np.linalg.solve` can take a really long time.

So I will try a few more things, and if that doesn't work, then I guess I will have to find a clever way for `Random`. Maybe, `rng` can be reutilized for the same `field`. That would limit the number of times `numpy.random.default_rng(seed)` is called, and use less OS entropy.

**Comment by iyanmv** [comment]
I think now `test_instantiation.py` should only consume one 'seed=None` at the very beginning when generating `SEEDS` iterator. But test still freezes... Any ideas?

**Comment by iyanmv** [comment]
Aha! Problem was not `test_instantiation.py`, but `test_linalg.py`. For some reason, without the verbose flag on `pytest`, we were not seeing the actual moment when the test "freezes" (actually, it just slooows down a lot). I think it's okay to have an array of seeds generated at once. Tomorrow I will carefully check all the modules, so I'm not missing any more cases.

**Comment by iyanmv** [comment]
I narrowed the issue down to the function `full_rank_matrix()` in `test_linalg.py`. For some reason, for the combination `ubuntu-latest` + `min-dependencies`, this takes forever, to the point that the array `SEEDS` is finished. Before adding this array, probably the entropy pool was finished (so it was failing silently), and before my changes, it was just taking longer (maybe even failing some times if taking more than 6 hours) but not finishing the entropy pool because only one initial seed was used.

Do you have any ideas about this?

At least now, I'm able to replicate locally by setting up a conda environment with `python=3.6` and using `requirements-min.txt`. This will help debug this.

**Comment by iyanmv** [comment]
Alright, finally figured this out! Your tests are actually a nice test suite for `numpy.random` :wink: 

Relevant bug in this case is [gh-16066](https://github.com/numpy/numpy/issues/16066), which causes `default_rng.integers(2**32)` to always return `0`. This is why `full_rank_matrix()` gets in an infinite loop. This bug was introduced, ironically, by the ["fix"](https://github.com/numpy/numpy/pull/14777) to [gh-14774](https://github.com/numpy/numpy/issues/14774) (which was the reason why I needed to bump to NumPy 1.17.3 at the beginning). So by bumping NumPy to 1.17.3 I solve one issue and introduce a different one. By the way, this is why tests were always failing for the field `GF(2^32)`.

I think the easiest solution is to require [NumPy>=1.18.4](https://numpy.org/devdocs/release/1.18.4-notes.html), which is the first version that is not affected by [gh-16066](https://github.com/numpy/numpy/issues/16066) or [gh-14774](https://github.com/numpy/numpy/issues/14774).

I will rebase and clean up "this mess" so you can review it. Fingers crossed tests are passed after all this :crossed_fingers:.

**Comment by iyanmv** [comment]
Okay, rebase done squashing everything in three different commits. I hope this is easy to review now. Sorry about all the noise above. I was writing here as I was testing, discovering and understanding things.

**Comment by mhostetter** [comment]
Good job working through those issues.

One minor thing, when bumping the minimum NumPy version you have to also change it here:

https://github.com/mhostetter/galois/blob/ab0f108923844fcfef0a0af095886fde7bcd89e1/setup.cfg#L49-L51

Something I'm considering / debating... since every `FieldArray.Random()` call gets a new seed, this code, which previously gave repeatable results, now wouldn't.

```python
In [1]: import numpy as np

In [2]: import galois

In [3]: GF = galois.GF(2**8)

In [4]: np.random.seed(123456789)

In [5]: GF.Random(10)
Out[5]: GF([184, 190, 103, 136, 156,  46, 155, 253,  50,  45], order=2^8)

In [6]: GF.Random(10)
Out[6]: GF([217,  23,  94,   3,  90,  17, 114, 130,  29,  67], order=2^8)
```

I'm wondering if when `seed` is `None` then the normal `np.random.randint()` should be called and if the seed is specified then `np.random.default_rng(seed).integers()` should be called? Do you have thoughts?

**Comment by iyanmv** [comment]
> One minor thing, when bumping the minimum NumPy version you have to also change it here:

Ups, okay, I will change that as well, later.

> Something I'm considering / debating... since every FieldArray.Random() call gets a new seed, this code, which previously gave repeatable results, now wouldn't.

> I'm wondering if when seed is None then the normal np.random.randint() should be called and if the seed is specified then np.random.default_rng(seed).integers() should be called? Do you have thoughts?

Mmm... I don't like the idea of mixing the old `np.random.*` with the new functions, but I do see your point. In any case, I think it's a good idea to stop using `np.random.seed()`.

By the way, before my changes, using `np.random.seed()` would also lead to irreproducible results for large finite fields with `dtype=numpy.object_` because `random` does not use the global numpy seed.

I will think a little bit more about this and let you know.

**Comment by iyanmv** [comment]
Would it be acceptable to have something like this?

```python
>> import numpy as np
>> import galois

>> GF = galois.GF(2**8)

>> rng = np.random.default_rng(123456789)

>> GF.Random(10, seed=rng)
GF([184, 190, 103, 136, 156,  46, 155, 253,  50,  45], order=2^8)

>> GF.Random(10, seed=rng)
GF([217,  23,  94,   3,  90,  17, 114, 130,  29,  67], order=2^8)
```

In this way, rng is initialized once and passed around. If you want to reset it, you just create a new rng with the same seed and pass it again. This would use the fact that the constructor `default_rng()` accepts a `Generator` as a seed. In this way, we could also make fields with `dtype=numpy.object_` reproducible. We could use the state of the `Generator` as seed for `random.seed()`.

**Comment by mhostetter** [comment]
> By the way, before my changes, using np.random.seed() would also lead to irreproducible results for large finite fields with dtype=numpy.object_ because random does not use the global numpy seed.

Yes, I did notice that. Great catch!

> In this way, rng is initialized once and passed around. If you want to reset it, you just create a new rng with the same seed and pass it again. This would use the fact that the constructor default_rng() accepts a Generator as a seed. In this way, we could also make fields with dtype=numpy.object_ reproducible. We could use the state of the Generator as seed for random.seed().

Yes, I like that approach. I had a similar idea floating around, but this works better.

Can you add the `Generator` as a valid input type to `seed` and add a little blurb in the "Parameters" section about what `seed` will do when `None`.

**Comment by iyanmv** [comment]
> Can you add the `Generator` as a valid input type to `seed` and add a little blurb in the "Parameters" section about what `seed` will do when `None`.

Yep, I will try to do the changes now so you can have a look.

**Comment by mhostetter** [comment]
@iyanmv all this looks good. Thanks for your work on it.

I just have one more suggested addition and then I'll merge in. Can we add a `seed=None` kwarg in `Poly.Random()`, i.e. `def Random(cls, degree, seed=None, field=GF2):`? It invokes `FieldArray.Random()`, so we should just pass along that seed to your newly-modified constructor.

https://github.com/mhostetter/galois/blob/ab0f108923844fcfef0a0af095886fde7bcd89e1/galois/_polys/_poly.py#L242-L285

**Comment by iyanmv** [comment]
Okay, done!

**Comment by iyanmv** [comment]
Hi @mhostetter, probably you are busy, but just wanted to be sure that I didn't forget to do any changes that you wanted. Please let me know.

**Comment by mhostetter** [comment]
@iyanmv yeah, sorry. I've just been busy from the American Thanksgiving holiday and the aftermath. I wanted to publish a new release after merging your PR. I'll try to do that today. You'll be credited in the release notes. Thanks for the help with getting these features in! Any more bugs, thoughts, or ideas are very welcome!

**Comment by iyanmv** [comment]
No worries, I also didn't touch the code for a while, so I was not sure if something else was missing. Thanks! Probably in one or two weeks I will be using galois a lot again, so if I see anything or have any thoughts I will open an issues or PR.

**Pull request merged**
