### PR TITLE
comulative patch

### PR DESCRIPTION
**Pull request by SergBobrovsky**
There is no point in trying to merge your and my code with separate commits - too much has been redone and reorganized, and the diff utility does not allow anybody to figure it out.
I just added my code in one piece at the bottom of the file, without changing anything at the top. This means that the PR will not pass the tests - it doesn't matter. This means that you can delete those variants of the functions of the same name that you like less.

changed prime_factors() 
fix carmichael(), prev_prime(), next_prime()
made chinese_remainder() small, fast and pretty
finally made primitive_roots(), hell-fast. 
primitive_root(1000000000000000035000061) == 7, it takes 10 sec on my 10yo PC (with a little cheating - I asked Wolfram, is it prime)

some functions  signatures changed, i.e. prime_factors(), primitive_roots(). I'll make PR for algorithms_test.py

### CODE REVIEW

**Comment by mhostetter** [comment]
Just curious, did you run `galois.primitive_root(1000000000000000035000061)` with the latest code?

I changed the algorithm to only work on prime `n` and it is significantly faster!

```python
In [1]: import galois                                                                                    

In [2]: galois.primitive_root(1000000000000000035000061)                                                 
Out[2]: 7

In [3]: %timeit galois.primitive_root(1000000000000000035000061)                                         
20.8 ms ± 165 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

**Comment by mhostetter** [comment]
I noticed you used `pow()` for modular exponentiation. i wasn't aware it could take a third argument for modulus. And native `pow` is significantly faster than my `galois.modular_exp`. i might do a wholesale replacement of `galois.modular_exp` with `pow`.

Great find!

```python
In [10]: pow(123465, 978654, 123)                                                                        
Out[10]: 9

In [11]: galois.modular_exp(123465, 978654, 123)                                                         
Out[11]: array(9)

In [12]: %timeit pow(123465, 978654, 123)                                                                
818 ns ± 8.45 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [13]: %timeit galois.modular_exp(123465, 978654, 123)                                                 
20.5 µs ± 220 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [14]: pow(123465123456, 978654321, 123456)                                                            
Out[14]: 107904

In [15]: galois.modular_exp(123465123456, 978654321, 123456)                                             
Out[15]: array(107904)

In [16]: %timeit pow(123465123456, 978654321, 123456)                                                    
1.95 µs ± 35 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [17]: %timeit galois.modular_exp(123465123456, 978654321, 123456)                                     
23.5 µs ± 228 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

**Comment by SergBobrovsky** [comment]
> Just curious, did you run `galois.primitive_root(1000000000000000035000061)` with the latest code?
Now I did. Replasing `modular_exp` to `pow`, I got the same 10 seconds for this huge num, but calling primitive_root(10), I got
> ValueError: This algorithm is optimized for prime `n`, not 10
Looks so-so. My code can primitive_root(10).
Rejecting non-prime nums thats have primitive roots make life easy, but we don't look for easy ways )

**Comment by mhostetter** [comment]
Yeah, I temporarily disabled `primitive_roots` for non-prime n. I planned to make it more general again.

I'd like to start by making a PR removing `modular_exp` and placing with `pow`. Are you ok with me referencing you and this PR in it?

**Comment by SergBobrovsky** [comment]
> Are you ok with me referencing you and this PR in it?

ok

**Pull request closed without merging**
