### PR TITLE
Make finding primitive roots general

### PR DESCRIPTION
**Pull request by mhostetter**
- [x] Remove `modular_exp()` in favor of python's native `pow()`, which is faster, as found by @SergBobrovsky in #46.
- [ ] Remove constraint that we only find primitive roots of primes.

### CODE REVIEW

**Comment by mhostetter** [comment]
Example of how much faster `pow()` is than `modular_exp()`.

```python
In [10]: pow(123465, 978654, 123)                                                                        
Out[10]: 9

In [11]: galois.modular_exp(123465, 978654, 123)                                                         
Out[11]: array(9)

In [12]: %timeit pow(123465, 978654, 123)                                                                
818 ns ± 8.45 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [13]: %timeit galois.modular_exp(123465, 978654, 123)                                                 
20.5 µs ± 220 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [14]: pow(123465123456, 978654321, 123456)                                                            
Out[14]: 107904

In [15]: galois.modular_exp(123465123456, 978654321, 123456)                                             
Out[15]: array(107904)

In [16]: %timeit pow(123465123456, 978654321, 123456)                                                    
1.95 µs ± 35 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [17]: %timeit galois.modular_exp(123465123456, 978654321, 123456)                                     
23.5 µs ± 228 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

**Comment by SergBobrovsky** [comment]
What the difference with my realization? Both based on Lagrange theorem, and I found my variant more elegant and concise, with 2 functions - primitive_root & primitive_roots.
If you'll takes only own commits, what is my role?
I proposed trace() function as a basic for many cases - a hope it's elegant approch. No consideration, no discussion, no rejection - just silence. Now I strongly improved it - so what?
I fixed for some broken functinos - ignored. What is my role here? Am I a contributor or just commentator?

**Comment by mhostetter** [comment]
> What the difference with my realization? Both based on Lagrange theorem, and I found my variant more elegant and concise, with 2 functions - primitive_root & primitive_roots.
> If you'll takes only own commits, what is my role?
> I proposed trace() function as a basic for many cases - a hope it's elegant approch. No consideration, no discussion, no rejection - just silence. Now I strongly improved it - so what?
> I fixed for some broken functinos - ignored. What is my role here? Am I a contributor or just commentator?

I told you I wanted to take your suggestion and use `pow()` not `modular_exp()`. That wasn't in your PR, so I added here.

I previously made `primitive_roots()` only work on primes, here I disabled it. i wanted slightly more functionality, `start`, `stop`, etc. I also wanted it documented and tested.

I am open to your implementation of the prime sieve and any improvements/bug fixes in any functions. Your previous PR #46 just had code at the bottom that wasn't ready to merge. Can you break your changes in single PRs? For isntance, the "fix `carmichael()`" change, can that be it's own PR? I'm not even sure that's Carmichael is broken, but we can discuss there.

Same with your changes to `primes`, `trace`, `next_prime`, `prev_prime`, can that be it's own PR? Same with the changes to the Chinese remainder theorem? That way we can discuss each on it's own. Also, it would be best if your changes continue to pass the unit tests.

Thanks, Matt.

**Comment by mhostetter** [comment]
Regarding the "generalizing primitive roots" commit, I can add you as a coauthor, if you'd like.

**Comment by mhostetter** [comment]
@SergBobrovsky I added you as a co-author here. I''m going to merge these changes in, then we can discuss your other work in their separate PRs. Thanks.

**Pull request merged**
